title:        Geographic Data Science Laboratory
tagline:      'Geographic Data Science Lab'
description:  'At the University of Liverpool'
url:    http://www.geographicdatascience.com
version:      1.1.1
author:
  name:       GDSL
  email:      alex.singleton@liverpool.ac.uk
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     6

