### GENERAL SETTINGS ###

# Site settings
title: Geographic Data Science Lab.
description: "The Geographic Data Science Laboratory (GDSL) was established at the University of Liverpool with the aim of creating a centre of excellence for research and teaching within this emerging area"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://geographicdatascience.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#4ECDC4" #"#F70031" 
  primary_rgb: "78,205,196" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#556270" #"#33004D"
  link: "#C44D58"
  link_hover: "#FF6B6B"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/geodatascience
  - title: linkedin
    url: https://www.linkedin.com/groups/7024427
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Department of Geography and Planning,
    - Roxby Building,
    - 74 Bedford St S, 
    - Liverpool
    -  L69 7ZT.
email: alex.singleton@liverpool.ac.uk
tel: 0151 7942860


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Alex Singleton
    position: Professor
    text: Geodemographics, urban systems, Data Science, mobilities / transport.
    img: alexsingleton.jpg
    social:
      - title: envelope #use for email address
        url: mailto:alex.singleton@liverpool.ac.uk
      - title: linkedin
        url: https://uk.linkedin.com/in/alexdsingleton
      - title: twitter
        url: http://twitter.com/alexsingleton
  - name: Dani Arribas-Bel
    position: Lecturer
    text: Cities, spatial analysis, statistics, open source computing, new forms of data.
    img: darribas.jpg
    social:
      - title: envelope #use for email address
        url: mailto:D.Arribas-Bel@liverpool.ac.uk
      - title: linkedin
        url: https://uk.linkedin.com/in/darribas
      - title: twitter
        url: http://twitter.com/darribas
  - name: Nick Bearman
    position: Research Associate & GIS Trainer
    text: Transport, reproducible research, open data, R, QGIS, sonification.
    img: nickbearman.jpg
    social:
      - title: envelope #use for email address
        url: mailto:n.bearman@liverpool.ac.uk
      - title: linkedin
        url: https://uk.linkedin.com/in/nickbearman
      - title: twitter
        url: http://twitter.com/nickbearmanuk
  - name: Alec Davies
    position: PhD Student 
    text: Health and lifestyle, fitness participation, healthy consumption
    img: alecdavis.jpg
    social:
        - title: envelope #use for email address
          url: mailto:sgadavi3@liverpool.ac.uk
        - title: linkedin
          url: https://uk.linkedin.com/in/alec-davies-464a21b3       
  - name: Michalis Pavlis
    position: Data Scientist
    text: Data Mining, Spatial Statistics, Scientific Computing, Open Source, Web
    img: michalis.JPG
    social:
      - title: envelope #use for email address
        url: mailto:mpavlis@liverpool.ac.uk
  - name: Les Dolega
    position: Data Scientist
    text: Retail, Resilience, Regional Studies, Geocomputation
    img: Les.jpg
    social:
      - title: envelope #use for email address
        url: mailto:L.Dolega@liverpool.ac.uk
  - name: Hai Nguyen
    position: Data Scientist
    text: Networks, knowledge-base systems, linked data, big data
    img: hainguyen.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Hai.Hoang.Nguyen@liverpool.ac.uk
  - name: Ellen Talbot
    position: PhD Student
    text: Transport, dynamic geodemographics, consumer behaviour
    img: ellen.jpg
    social:
      - title: envelope #use for email address
        url: mailto:e.talbot@liverpool.ac.uk
  - name: Kaisa Lahtinen
    position: PhD Student
    text: Neighbourhood structure, zone design, survey data
    img: KaisaLahtinen.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Kaisa.Lahtinen@city.ac.uk
 - name: Linda Wood
    position: PhD Student
    text: Data science, spatial analysis, social statistics, big data, retail
    img: linda.jpg
    social:
      - title: envelope #use for email address
        url: mailto:l.blade@liverpool.ac.uk
  - name: Dean Riddlesden
    position: Data Scientist / Industry Partner
    text: Retail, Internet Geography, Big Data, Broadband
    img: dean.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Dean.Riddlesden@boots.co.uk
      - title: linkedin
        url: https://www.linkedin.com/in/dean-riddlesden-40136354
      - title: twitter
        url: https://twitter.com/deanriddlesden
  - name: Alekos Alexiou
    position: PhD Student
    text: Geodemographics, clustering, MAUP, R, open data
    img: alekos.jpg
    social:
      - title: envelope #use for email address
        url: mailto:A.Alexiou@liverpool.ac.uk
      - title: linkedin
        url: http://linkedin.com/in/alalexiou       
# Clients information. Shown on Home and About pages.
clients:
  - name: ESRC
    img: Esrc_logo.png
  - name: University of Liverpool
    img: uolLogo.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Geographic Data Science is about making sense of how our world works; turning new forms of data into information that we can use to make intelligent decisions"

